[package]
name = "async_dag_comparison"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
color-eyre = "0"

# async
tokio = { version = "1", features = ["full"] }

async_dag = "0"
taski = { path = "../../" }
