name: feature-matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "the feature matrix"
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    name: Compute feature matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.feature-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: romnn/cargo-feature-combinations@main

      - name: Compute feature matrix
        id: feature-matrix
        run: >-
          echo "matrix=$(cargo fc matrix)"
          >> "$GITHUB_OUTPUT"
