name: release
on:
  push:
    tags:
      - "*"
jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish-crate:
    needs: [tests]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates
        uses: romnn/publish-crates@main
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          resolve-versions: true
          publish-delay: 30s
